# Generated by Django 5.2.9 on 2025-12-25 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        # NOTE: Depending on a late Saleor product migration blocks our inventory tables in fresh/prod DBs.
        # We only need ProductVariant to exist; `__first__` allows us to run after the product app starts.
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='branches.branch')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventory', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Branch Inventory',
                'verbose_name_plural': 'Branch Inventory',
                'db_table': 'branch_inventory',
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('current_quantity', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('acknowledged_by', models.CharField(blank=True, max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.branchinventory')),
            ],
            options={
                'verbose_name': 'Low Stock Alert',
                'verbose_name_plural': 'Low Stock Alerts',
                'db_table': 'low_stock_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('RETURN', 'Return')], max_length=20)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='branches.branch')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=100, unique=True)),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='branches.branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'db_table': 'stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='branchinventory',
            index=models.Index(fields=['product_variant', 'branch'], name='branch_inve_product_2cf110_idx'),
        ),
        migrations.AddIndex(
            model_name='branchinventory',
            index=models.Index(fields=['branch', 'quantity'], name='branch_inve_branch__2bcdac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchinventory',
            unique_together={('product_variant', 'branch')},
        ),
        migrations.AddIndex(
            model_name='lowstockalert',
            index=models.Index(fields=['status', 'created_at'], name='low_stock_a_status_8c09aa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'created_at'], name='stock_movem_branch__bff82f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product_variant', 'created_at'], name='stock_movem_product_0c20f3_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_branch', 'status'], name='stock_trans_from_br_e9936e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_branch', 'status'], name='stock_trans_to_bran_ccde05_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['transfer_number'], name='stock_trans_transfe_2376ec_idx'),
        ),
    ]
